### ISSUE TITLE
[Bug] 댓글 집계 시, 대댓글은 포함 안 되는 현황

### ISSUE THREAD

**Issue by GBGreenBravo** [Kernel360/E2E1-Orury#168]
## 버그 내용  
댓글 집계 시, 대댓글은 댓글 수에 포함 안 

### 사용자 환경  
AOS

### 버그 발생 이전 상황  
게시글 목록 화면에서 각 게시글에 대한 댓글 수가 표시돼 있는데, 이 집계에 대댓글은 포함이 안 돼있습니다!

### 정상 작동 시 기대현상
기획의 방향성 같아보이긴 하지만, 조심스럽게 대댓글도 댓글 수에 집계하는 것이 더 좋아보인다는 개인적인 의견 추가드립니다!  

### 스크린샷
![KakaoTalk_Photo_2023-11-22-11-26-09 001](https://github.com/Kernel360/E2E1-Orury/assets/147565215/de53cb89-16f5-42de-89a8-1d7f0ef46437)
![KakaoTalk_Photo_2023-11-22-11-26-10 002](https://github.com/Kernel360/E2E1-Orury/assets/147565215/7fc25b26-5e05-45fd-b881-34498a6bf69c)

**Comment by mooncw** [comment]
버그 제보 감사합니다.
