### ISSUE TITLE
[Bug] 댓글 좋아요 표시 및 동작 이슈

### ISSUE THREAD

**Issue by linglong67** [Kernel360/E2E1-Orury#169]
## 버그 내용  
댓글 좋아요가 다른 곳에 표시되고 그 이후에 좋아요 수정이 안되요

### 사용자 환경  
- [x] AOS
- [ ] IOS

### 버그 발생 이전 상황 
댓글, 대댓글 여러 개 작성하고 좋아요 눌러보고 있었습니다

### 정상 작동 시 기대현상 
대댓글에 빨간 하트가 표시되고, 아래 댓글은 빈 하트가 나와야될 것 같아요
그리고 저거 다시 수정하려고 해봐도 동작을 안해요

### 스크린샷
![image](https://github.com/Kernel360/E2E1-Orury/assets/88479739/2d63e4d7-28ef-4147-a959-7b1c7013d204)

**Comment by mooncw** [comment]
버그 제보 감사합니다.
