### ISSUE TITLE
패키지 경로 문제 외 몇 가지

### ISSUE THREAD

**Issue by ShineCorine** [Kernel360/E2E1-Orury#33]
### 버그 내용

제 컴퓨터에서는 다음과 같은 내용들이 문제가 있어 보입니다. 다른 분들도 확인 부탁드려요

- [x] 제 컴퓨터에서는 BoardEntity.java  43번 라인에 @Where(clause = "isDeleted = false") 에서 에러가 납니다. 
 @Where(clause = "is_delete = false")이렇게 바꾸니 에러가 안 나는데 다른 분들도 같은지 확인 부탁드려요

- [x] PostRequest.java  id에 붙은 어노테이션이 @NotBlank로 되어 있는데 찾아보니 gpt에게 물어보니 String 타입일 때 쓰는 게 맞는지 , 그렇다면 없 애거나 NotNull 같은거 붙여야 하는지 의견 확인 부탁드려요

- [x] PostViewRequest.java  1번 패키지 경로가 package com.kernel360.orury.domain.post; 에서 package com.kernel360.orury.domain.post.model; 로 바꾸는 게 맞는지 확인해주세요

이게 맞으면 아래 내용들도 다음과 같이 수정해야 할 것 같습니다.

- [ ] PostController.java  2번 라인 import com.kernel360.orury.domain.post.PostViewRequest;-> import com.kernel360.orury.domain.post.model.PostViewRequest; 

- [ ] PostService.java 파일에서  import com.kernel360.orury.domain.post.PostViewRequest; -> import com.kernel360.orury.domain.post.model.PostViewRequest;

**Comment by kkkapuq** [comment]
1. `@Where` 어노테이션의 요소는 snake_case로 작성되어야 합니다. `@Where` 관련 블로그 내용 전달드립니다.
https://jaime-note.tistory.com/450

2. 해당 건 관련 이슈 올리겠습니다.

3. p`ackage com.kernel360.orury.domain.post.model`로 수정이 필요해보입니다. upstream의 develop엔 post 로 올라와있네요
