### ISSUE TITLE
메시지 및 상수 패키지 처리

### ISSUE THREAD

**Issue by kkkapuq** [Kernel360/E2E1-Orury#58]
### 이슈 관련 도메인 (회원, 게시판, etc..)
전역

### 목적
중복코드를 방지하기 위한 메시지와 상수 패키징 작업

### 상세 내용
- 메시지와 상수 별도로 구분 예정

**Comment by corazzon** [comment]
메시지와 상수를 분리해서 관리하도록 한 점이 좋네요. 나중에 다국어 지원시에도 더 유리하게 작업할 수 있도록 개선해 주셨네요 👍
